### ISSUE TITLE
Missing building/installation procedure

### ISSUE THREAD

**Issue by hyviquel** [Pikciochain/PythonSDK#1]
Hi,

I am trying to setup the SDK on my machine but I am missing some information:
is running `python setup.py build` the correct way to do it? is using virtualenv would be a good practice here? Is it compatible with python 2 and/or 3?
Could you **write** the installation procedure in the README or in an INSTALL file?

Thanks

**Comment by jorickMuB** [comment]
Hello @hyviquel 
We are currently build a more up to date install file. We also preparing a video walkthrough for setting a node and plug to API using the Python SDK.
It is currently running on Python 2.7
Best
